BE Reivew 요청용 커밋
codesquad-member-2020/dust-1 pull request #107
Opened 2020-04-03 09:32 UTC by ksundong

감사합니다.

고생하셨습니다. @beginin15

2020-04-03 09:35 UTC, beginin15 commented
@ksundong 디온이야말로 고생많았어요~

2020-04-04 01:15 UTC, wheejuni requested changes
수고 많으셨습니다. ㅠㅠ
딱 봐도 공공API 호출이 쉽지 않아보이네요.
리팩토링에 참고 되면 좋겠습니다.

2020-04-04 01:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/team1/dust/constants/KakaoAPIConstants.java
> +    public static String KAKAO_API_APP_KEY = "6241f25eb7531c4b1eca36dd65c4b709";
이런 값은 하드코딩보단 properties 파일에 관리해주면 좋습니다.
실행환경에 따라 키가 달라질 수도 있어서요.

2020-04-04 01:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/team1/dust/constants/KakaoAPIConstants.java
> +    public static String AND_Y = "&y=";
이정도는 따로 이렇게 관리할 필욘 없습니다...

2020-04-04 01:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/team1/dust/domain/Forecast.java
> +}
이제는 `toString()` 정도는 IDE의 자동 생성에 맡겨도 됩니다!

2020-04-04 01:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/team1/dust/util/ResourceUtils.java
> +    private static void excuteGIFSplit(String command) {
`execute` 가 맞습니다.

2020-04-04 01:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/team1/dust/util/ResourceUtils.java
> +            }
Java에서 네이티브 콜 하는 코드 작성 가급적 삼가해 주시고요,
이미지의 변환/생성을 담당하는 Java 진영의 꽤 유명한 라이브러리들이 있습니다. 이미지 마술이었나 마법이었나.... 물론 이런 라이브러리들도 내부적으론 커맨드 라인을 실행하겠지만, 우리가 직접 짜는 것보단 안정성이나 사용성이 훨씬 높고 유지보수하기도 쉽습니다. 
직접 시스템 명령어는 호출하지 말아주세요.

2020-04-04 01:15 UTC, wheejuni commented on BE/src/test/java/com/codesquad/team1/dust/domain/DustStatusTest.java
> +        log.debug("JsonNode로 DustStatus 객체를 생성하는데 성공하였습니다.");
`assert` 했는데 로그를 찍은 이유가 있나요?

2020-04-04 01:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/team1/dust/util/PublicAPIUtils.java
> +        ObjectMapper mapper = new ObjectMapper();
`ObjectMapper` 가 반복적으로 사용되므로 Spring Bean으로 관리하는 방법을 고려해봐도 될듯 합니다. 
지금은 맵퍼의 기본 기능만 사용하고 있지만, 나중에 부가 기능이나 옵션을 추가할 상황도 생길텐데, 생성자로 넘기는 경우 중복 코드가 발생하게 되니까요. 

이런 종류의 객체를 Spring Bean으로 관리할 때는 Javadoc을 꼼꼼히 살펴보고 thread safety를 파악해야 할 겁니다. 
https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ObjectMapper.html 여기에 따르면 이 클래스는 thread safe하네요.

2020-04-04 01:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/team1/dust/domain/Forecast.java
> +}
아 자동생성 한거군요

2020-04-04 01:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/team1/dust/constants/PublicAPIConstants.java
> +    public static final String PUBLIC_API_SERVICE_KEY = "qh1W9WhS1Wl%2BH90EXv4PO2hR1k11hXsBngVTfuehLCm%2BxDFqBzITeVMij4tmxljJSyA%2FstR9HRpfidM6Vi%2BG3Q%3D%3D";
이것도 프로퍼티로 관리해주세요.

2020-04-04 01:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/team1/dust/api/MockFineDustApiController.java
> +    @GetMapping("/location/@={latitude},{longitude}")
음 Path가 좀 이상한데요? 쿼리스트링을 사용하는 게 낫지 않았을까요.

2020-04-04 01:15 UTC, wheejuni commented on BE/src/main/java/com/codesquad/team1/dust/api/MockFineDustApiController.java
> +        dustStatusList.add(new DustStatus("2", "51", "2020-03-30 12:00"));
흠.... 이거 요청이 들어올때마다 이 코드가 실행될텐데...
제가 자세한 백그라운드를 잘 모르겠어서 뭐라 리뷰드리기가 좀 어렵네요. 혹시 배경을 알 수 있을까요.

2020-04-04 01:31 UTC, ksundong commented on BE/src/main/java/com/codesquad/team1/dust/constants/KakaoAPIConstants.java
> +    public static String KAKAO_API_APP_KEY = "6241f25eb7531c4b1eca36dd65c4b709";
아하 전에 테스트 코드로 Properties 값 읽어오는 코드를 본 적이 있는 것 같습니다.
여기서 적용하면 되겠네요!
감사합니다.

2020-04-04 01:31 UTC, ksundong commented on BE/src/main/java/com/codesquad/team1/dust/constants/KakaoAPIConstants.java
> +    public static String AND_Y = "&y=";
😅

2020-04-04 01:32 UTC, ksundong commented on BE/src/main/java/com/codesquad/team1/dust/domain/Forecast.java
> +}
네 자동생성 기능을 이용하였습니다!

2020-04-04 01:33 UTC, ksundong commented on BE/src/test/java/com/codesquad/team1/dust/domain/DustStatusTest.java
> +        log.debug("JsonNode로 DustStatus 객체를 생성하는데 성공하였습니다.");
특별한 이유는 없습니다!

2020-04-04 01:34 UTC, ksundong commented on BE/src/main/java/com/codesquad/team1/dust/util/PublicAPIUtils.java
> +        ObjectMapper mapper = new ObjectMapper();
좋은 리뷰 감사합니다. Bean으로 등록하면 되는군요...
안그래도 여러 부분에서 공통적으로 쓰이는데, 이게 영향을 주는지 확인할 생각을 안했던 것 같습니다.
직접 찾아봐주시고... 감사합니다!

>이런 종류의 객체를 Spring Bean으로 관리할 때는 Javadoc을 꼼꼼히 살펴보고 thread safety를 파악해야 할 겁니다.

기억해두겠습니다!

2020-04-04 01:34 UTC, ksundong commented on BE/src/main/java/com/codesquad/team1/dust/constants/PublicAPIConstants.java
> +    public static final String PUBLIC_API_SERVICE_KEY = "qh1W9WhS1Wl%2BH90EXv4PO2hR1k11hXsBngVTfuehLCm%2BxDFqBzITeVMij4tmxljJSyA%2FstR9HRpfidM6Vi%2BG3Q%3D%3D";
넵!

2020-04-04 01:36 UTC, ksundong commented on BE/src/main/java/com/codesquad/team1/dust/api/MockFineDustApiController.java
> +    @GetMapping("/location/@={latitude},{longitude}")
예시 그대로 따라하다보니... 지금보니까 이상하긴 하네요.
`?latitude=value&longitude=value` 쪽이 클라이언트나 서버 입장에서도 더 좋을 것 같아요.

2020-04-04 01:38 UTC, ksundong commented on BE/src/main/java/com/codesquad/team1/dust/api/MockFineDustApiController.java
> +        dustStatusList.add(new DustStatus("2", "51", "2020-03-30 12:00"));
원래는 Mock API를 일시적으로 제공하다가, 실제 API로 전환을 했었는데,
실제 데이터가 너무 균일하게 들어와서 Mock API를 다시 제공해주는게 어떻겠냐는 의견에 다시 추가한 코드입니다.
지금 보니까 이걸 그냥 담아놓고 주면 더 빠르게 응답할 수 있었겠네요.

2020-04-05 08:28 UTC, beginin15 commented on BE/src/main/java/com/codesquad/team1/dust/util/ResourceUtils.java
> +            }
참고하겠습니다!

2020-04-18 10:03 UTC, closed without merging